FROM --platform=linux/amd64 python:3.9-slim
WORKDIR /app
COPY requirements.1a.txt .
RUN pip install --no-cache-dir -r requirements.1a.txt
COPY solution_1a.py .
RUN mkdir -p /app/input /app/output
CMD ["python", "solution_1a.py"]